---
server:
  # The path to the static resources for officectl (deprecated; for the reset
  # password page of officectl). Can be overridden with the --static-data-dir
  # command line option.
  static_data_dir: /usr/share/officectl/
  # The secret used to sign the JWT authentication token. Can be overridden with
  # the --jwt-secret command line option.
  jwt_secret: awesome_secret
  # The hostname to bind to for listening. Defaults to localhost if not set.
  # Can be overridden using the --hostname command line option.
#  hostname: 127.0.0.1
  # The port to bind to for listening. Defaults to 8080 if not set.
  # Can be overridden using the --port command line option.
#  port: 8080



# Optional: This is an alias to main domain mapping.
#domain_aliases:
#  example.net: example.org


# The directory that will be used for authentication in officectl. Currently
# only an “internal_openldap” directory type is supported.
#auth_service_id: ldap

# The list of services supported through officectl.
services:
  # The LDAP config. All fields are required, except for the people_dn as not
  # all commands using LDAP require it (for commands that do require it, if it
  # is not set, the command will fail, obviously).
  # Important: The people_dn is relative to the base_dn (of the current domain).
  #            It can be empty, in which case, people will be directly in the
  #            base dn.
#  ldap:
#    name: LDAP
#    provider: internal_openldap
#    provider_config:
#      url: ldaps://your.ldap.server
#      admin_username: cn=admin,dc=example,dc=org
#      admin_password: this_password_is_secure
#      officectl_admin_groups_dn:
#      - cn=admin,ou=groups,dc=example,dc=org
#      people_dn: ou=people
#      base_dn_per_domains:
#        example.org: dc=example,dc=org
  # The Google config. The superuser_json_creds field is required. The admin
  # email is needed for commands that requires officectl to become a superadmin
  # (create users, change password, etc.). The domains key should contain the
  # list of _primary_ domains of the Google account.
#  ggl:
#    name: Google Apps
#    provider: internal_google
#    provider_config:
#      admin_email: admin@example.net
#      superuser_json_creds: /path/to/creds.json
#      domains:
#      - example.net
#      - mail.example.net
  # The GitHub config. All fields are required.
#  github:
#    name: GitHub
#    provider: internal_github
#    provider_config:
#      private_key_path: /path/to/key.pem
#      app_id: 12345
#      install_id: 12345
  # Give the opportunity to link any service via an HTTP service proxy. The
  # communication is secured with https, and communication is authenticated
  # using the JWT secret. See officectl doc for more info.
#  non_built_in_directory:
#    name: The Provider Name
#    provider: http_service_v1
#    provider_config:
#      url: https://your_service.net/officectl
#      jwt_secret: this_is_a great_secret

# vim: ts=2 sw=2 et
